import type { TriviaQuestion } from "../../types/book-types";

export const indiaQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of India?",
    options: ["Mumbai", "New Delhi", "Chennai", "Kolkata"],
    correctAnswer: 1,
    explanation: "New Delhi is the capital city of India.",
  },
  {
    id: 2,
    question: "Which river is considered the most sacred in India?",
    options: ["Godavari", "Ganga", "Yamuna", "Narmada"],
    correctAnswer: 1,
    explanation: "The Ganga (Ganges) River is regarded as sacred by millions of Hindus.",
  },
  {
    id: 3,
    question: "Who was the leader of the Indian independence movement?",
    options: ["Subhash Chandra Bose", "Jawaharlal Nehru", "Mahatma Gandhi", "B. R. Ambedkar"],
    correctAnswer: 2,
    explanation:
      "Mahatma Gandhi led India’s non-violent struggle for independence from British rule.",
  },
  {
    id: 4,
    question: "What is the national animal of India?",
    options: ["Elephant", "Lion", "Tiger", "Leopard"],
    correctAnswer: 2,
    explanation: "The Bengal tiger is the national animal of India.",
  },
  {
    id: 5,
    question: "Which festival is known as the Festival of Colors?",
    options: ["Diwali", "Eid", "Navratri", "Holi"],
    correctAnswer: 3,
    explanation: "Holi is a spring festival celebrated with colors across India.",
  },
  {
    id: 6,
    question: "What is the official currency of India?",
    options: ["Rupee", "Dollar", "Taka", "Yen"],
    correctAnswer: 0,
    explanation: "The Indian Rupee (INR) is the official currency of India.",
  },
  {
    id: 7,
    question: "Where is the Taj Mahal located?",
    options: ["Delhi", "Jaipur", "Varanasi", "Agra"],
    correctAnswer: 3,
    explanation: "The Taj Mahal is located in Agra and is a UNESCO World Heritage Site.",
  },
  {
    id: 8,
    question: "Which Indian state is famous for its backwaters?",
    options: ["Kerala", "Goa", "Tamil Nadu", "Assam"],
    correctAnswer: 0,
    explanation: "Kerala is known for its network of serene backwaters and houseboats.",
  },
  {
    id: 9,
    question: "Which dance form originates from Tamil Nadu?",
    options: ["Kathak", "Odissi", "Bharatanatyam", "Kuchipudi"],
    correctAnswer: 2,
    explanation: "Bharatanatyam is a classical Indian dance form from Tamil Nadu.",
  },
  {
    id: 10,
    question: "What is the Indian national flower?",
    options: ["Rose", "Sunflower", "Lotus", "Marigold"],
    correctAnswer: 2,
    explanation: "The lotus is the national flower of India, symbolizing purity and beauty.",
  },
];

export const chinaQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of China?",
    options: ["Shanghai", "Beijing", "Guangzhou", "Hong Kong"],
    correctAnswer: 1,
    explanation: "Beijing is the capital city and one of the most historic cities in China.",
  },
  {
    id: 2,
    question: "What is the Great Wall of China primarily made of?",
    options: ["Steel", "Stone and bricks", "Wood", "Bamboo"],
    correctAnswer: 1,
    explanation: "The Great Wall is primarily made of stone, bricks, and tamped earth.",
  },
  {
    id: 3,
    question: "Which Chinese philosopher founded Confucianism?",
    options: ["Laozi", "Sun Tzu", "Confucius", "Zhuangzi"],
    correctAnswer: 2,
    explanation: "Confucius was a Chinese philosopher and teacher who founded Confucianism.",
  },
  {
    id: 4,
    question: "What is the Chinese zodiac animal for 2024?",
    options: ["Rat", "Tiger", "Dragon", "Rabbit"],
    correctAnswer: 3,
    explanation: "2024 is the Year of the Rabbit in the Chinese zodiac cycle.",
  },
  {
    id: 5,
    question: "Which river is the longest in China?",
    options: ["Yellow River", "Yangtze River", "Pearl River", "Mekong River"],
    correctAnswer: 1,
    explanation:
      "The Yangtze River is the longest river in China and the third longest in the world.",
  },
  {
    id: 6,
    question: "Which city is known as the financial hub of China?",
    options: ["Beijing", "Chengdu", "Shanghai", "Xi'an"],
    correctAnswer: 2,
    explanation: "Shanghai is a major global financial center and the largest city in China.",
  },
  {
    id: 7,
    question: "What is the name of China’s high-speed rail system?",
    options: ["Bullet Line", "CRH", "Shinkansen", "Red Arrow"],
    correctAnswer: 1,
    explanation: "China Railway High-speed (CRH) is the branding for high-speed rail in China.",
  },
  {
    id: 8,
    question: "What is China’s official currency?",
    options: ["Yuan", "Won", "Renminbi", "Ruble"],
    correctAnswer: 2,
    explanation: "Renminbi is the official currency; the yuan is its basic unit.",
  },
  {
    id: 9,
    question: "Which festival marks the lunar new year in China?",
    options: [
      "Dragon Boat Festival",
      "Mid-Autumn Festival",
      "Spring Festival",
      "Qingming Festival",
    ],
    correctAnswer: 2,
    explanation:
      "The Spring Festival, or Chinese New Year, marks the beginning of the lunar calendar year.",
  },
  {
    id: 10,
    question: "Which traditional Chinese dish is made of dumplings?",
    options: ["Baozi", "Zongzi", "Jiaozi", "Tangyuan"],
    correctAnswer: 2,
    explanation: "Jiaozi are Chinese dumplings often eaten during Lunar New Year.",
  },
];

export const japanQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Japan?",
    options: ["Kyoto", "Tokyo", "Osaka", "Hiroshima"],
    correctAnswer: 1,
    explanation: "Tokyo is the capital and largest metropolitan area in Japan.",
  },
  {
    id: 2,
    question: "What is the traditional Japanese garment called?",
    options: ["Hanbok", "Kimono", "Qipao", "Sari"],
    correctAnswer: 1,
    explanation: "The kimono is a traditional Japanese robe worn on special occasions.",
  },
  {
    id: 3,
    question: "Which mountain is the tallest in Japan?",
    options: ["Mount Aso", "Mount Hiei", "Mount Fuji", "Mount Tate"],
    correctAnswer: 2,
    explanation: "Mount Fuji is Japan's tallest and most iconic mountain.",
  },
  {
    id: 4,
    question: "What is sushi traditionally wrapped in?",
    options: ["Lettuce", "Rice paper", "Seaweed", "Banana leaf"],
    correctAnswer: 2,
    explanation: "Sushi is commonly wrapped in seaweed called nori.",
  },
  {
    id: 5,
    question: "Which religion is indigenous to Japan?",
    options: ["Taoism", "Shinto", "Buddhism", "Confucianism"],
    correctAnswer: 1,
    explanation: "Shinto is Japan's native religion, centered around kami (spirits).",
  },
  {
    id: 6,
    question: "What is the Japanese art of paper folding called?",
    options: ["Ikebana", "Origami", "Sumi-e", "Calligraphy"],
    correctAnswer: 1,
    explanation: "Origami is the traditional Japanese art of paper folding.",
  },
  {
    id: 7,
    question: "Which Japanese food is a type of noodle?",
    options: ["Miso", "Sashimi", "Udon", "Tempura"],
    correctAnswer: 2,
    explanation: "Udon is a thick wheat flour noodle commonly eaten in Japan.",
  },
  {
    id: 8,
    question: "What is Japan’s famous high-speed train called?",
    options: ["TGV", "Maglev", "Shinkansen", "SkyRail"],
    correctAnswer: 2,
    explanation: "The Shinkansen is Japan’s bullet train known for speed and punctuality.",
  },
  {
    id: 9,
    question: "Which city is known for its temples and geisha culture?",
    options: ["Osaka", "Kyoto", "Nagoya", "Sapporo"],
    correctAnswer: 1,
    explanation: "Kyoto is famous for its historical temples, shrines, and geisha traditions.",
  },
  {
    id: 10,
    question: "What is the name of Japan’s national flower?",
    options: ["Lotus", "Orchid", "Cherry Blossom", "Sunflower"],
    correctAnswer: 2,
    explanation: "The cherry blossom (sakura) is Japan’s national flower and symbol of spring.",
  },
];

export const thailandQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Thailand?",
    options: ["Chiang Mai", "Bangkok", "Phuket", "Pattaya"],
    correctAnswer: 1,
    explanation: "Bangkok is the capital and most populous city of Thailand.",
  },
  {
    id: 2,
    question: "Which festival in Thailand involves large water fights?",
    options: ["Loy Krathong", "Songkran", "Yi Peng", "Vesak"],
    correctAnswer: 1,
    explanation: "Songkran is the Thai New Year festival known for nationwide water fights.",
  },
  {
    id: 3,
    question: "Which animal is a national symbol and highly revered in Thailand?",
    options: ["Tiger", "Elephant", "Monkey", "Peacock"],
    correctAnswer: 1,
    explanation: "Elephants are a national symbol of Thailand and play a major cultural role.",
  },
  {
    id: 4,
    question: "What is the currency of Thailand?",
    options: ["Ringgit", "Baht", "Rupee", "Dong"],
    correctAnswer: 1,
    explanation: "The Thai Baht is the official currency of Thailand.",
  },
  {
    id: 5,
    question: "What is Thailand’s most famous noodle dish?",
    options: ["Pho", "Pad Thai", "Laksa", "Udon"],
    correctAnswer: 1,
    explanation: "Pad Thai is Thailand’s most popular stir-fried noodle dish.",
  },
  {
    id: 6,
    question: "Which religion is followed by the majority of Thai people?",
    options: ["Christianity", "Hinduism", "Buddhism", "Islam"],
    correctAnswer: 2,
    explanation: "Buddhism is practiced by the vast majority of Thai citizens.",
  },
  {
    id: 7,
    question: "Which island is known for its Full Moon Party?",
    options: ["Koh Samui", "Koh Tao", "Koh Phangan", "Koh Phi Phi"],
    correctAnswer: 2,
    explanation: "Koh Phangan is famous for its monthly Full Moon Party on Haad Rin Beach.",
  },
  {
    id: 8,
    question: "What is the name of Thailand’s traditional dance drama?",
    options: ["Kabuki", "Bharatanatyam", "Khon", "Samba"],
    correctAnswer: 2,
    explanation: "Khon is a classical masked dance drama from Thailand.",
  },
  {
    id: 9,
    question: "Which structure is commonly found at Thai Buddhist temples?",
    options: ["Minaret", "Pagoda", "Stupa", "Ziggurat"],
    correctAnswer: 2,
    explanation: "Stupas are dome-shaped structures used to house Buddhist relics in Thailand.",
  },
  {
    id: 10,
    question: "Which flower is commonly used in Thai religious offerings?",
    options: ["Rose", "Lotus", "Jasmine", "Orchid"],
    correctAnswer: 1,
    explanation: "The lotus is a sacred flower in Buddhism and commonly used in offerings.",
  },
];

export const southKoreaQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of South Korea?",
    options: ["Busan", "Seoul", "Incheon", "Daegu"],
    correctAnswer: 1,
    explanation: "Seoul is the capital and largest city of South Korea.",
  },
  {
    id: 2,
    question: "What is the name of Korea’s writing system?",
    options: ["Kanji", "Katakana", "Hangul", "Hanja"],
    correctAnswer: 2,
    explanation: "Hangul is the Korean alphabet, created in the 15th century.",
  },
  {
    id: 3,
    question: "What is the traditional Korean dish made of fermented vegetables?",
    options: ["Tteokbokki", "Bibimbap", "Kimchi", "Japchae"],
    correctAnswer: 2,
    explanation: "Kimchi is a spicy, fermented vegetable dish and a Korean staple.",
  },
  {
    id: 4,
    question: "Which Korean martial art is known for its high kicks?",
    options: ["Judo", "Taekwondo", "Karate", "Kung Fu"],
    correctAnswer: 1,
    explanation: "Taekwondo is a Korean martial art known for fast kicks and agility.",
  },
  {
    id: 5,
    question: "What is the name of the border between North and South Korea?",
    options: ["Ceasefire Line", "Armistice Zone", "Peace Strip", "DMZ"],
    correctAnswer: 3,
    explanation: "The Demilitarized Zone (DMZ) separates North and South Korea.",
  },
  {
    id: 6,
    question: "What is the traditional Korean clothing called?",
    options: ["Kimono", "Hanbok", "Qipao", "Cheongsam"],
    correctAnswer: 1,
    explanation: "Hanbok is Korea’s traditional clothing, worn during festivals and ceremonies.",
  },
  {
    id: 7,
    question: "What is South Korea's national flower?",
    options: ["Lotus", "Cherry Blossom", "Rose of Sharon", "Lily"],
    correctAnswer: 2,
    explanation: "The Rose of Sharon (Mugunghwa) is the national flower of South Korea.",
  },
  {
    id: 8,
    question: "Which South Korean group gained global fame with the song 'Dynamite'?",
    options: ["BLACKPINK", "EXO", "BIGBANG", "BTS"],
    correctAnswer: 3,
    explanation: "BTS became globally popular with hits like 'Dynamite' and 'Butter.'",
  },
  {
    id: 9,
    question: "Which mountain is the tallest in South Korea?",
    options: ["Seoraksan", "Hallasan", "Taebaeksan", "Jirisan"],
    correctAnswer: 1,
    explanation: "Hallasan, located on Jeju Island, is the highest peak in South Korea.",
  },
  {
    id: 10,
    question: "What is the name for Korean historical dramas?",
    options: ["K-sageuk", "Hanji", "Sageuk", "Hwarang"],
    correctAnswer: 2,
    explanation: "Sageuk refers to South Korean TV dramas and films set in historical periods.",
  },
];

export const singaporeQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital of Singapore?",
    options: ["Singapore City", "Sentosa", "Marina Bay", "Changi"],
    correctAnswer: 0,
    explanation: "Singapore is a city-state, so its capital is Singapore itself.",
  },
  {
    id: 2,
    question: "Which popular attraction has a boat-shaped structure on top?",
    options: ["Esplanade", "Gardens by the Bay", "Marina Bay Sands", "Raffles Hotel"],
    correctAnswer: 2,
    explanation: "Marina Bay Sands is an iconic resort with a ship-shaped SkyPark on top.",
  },
  {
    id: 3,
    question: "What is Singapore’s main airport called?",
    options: ["Hong Kong Airport", "Marina Airport", "Changi Airport", "Penang Airport"],
    correctAnswer: 2,
    explanation: "Changi Airport is Singapore’s world-renowned international airport.",
  },
  {
    id: 4,
    question: "Which language is NOT an official language of Singapore?",
    options: ["English", "Malay", "Tamil", "Hindi"],
    correctAnswer: 3,
    explanation: "Hindi is not one of Singapore’s four official languages.",
  },
  {
    id: 5,
    question: "What is the Merlion?",
    options: ["A flower", "A dish", "A mythical creature", "A hotel"],
    correctAnswer: 2,
    explanation: "The Merlion is Singapore's mythical half-lion, half-fish symbol.",
  },
  {
    id: 6,
    question: "Which garden in Singapore features Super Trees?",
    options: ["Botanic Gardens", "Gardens by the Bay", "Bukit Timah", "Mount Faber Park"],
    correctAnswer: 1,
    explanation: "Gardens by the Bay is home to Singapore’s iconic Super Trees.",
  },
  {
    id: 7,
    question: "Which traditional district is known for its colorful shophouses and Malay culture?",
    options: ["Chinatown", "Kampong Glam", "Little India", "Holland Village"],
    correctAnswer: 1,
    explanation: "Kampong Glam is rich in Malay and Arab heritage, featuring vibrant shophouses.",
  },
  {
    id: 8,
    question: "What is the name of Singapore's national dish?",
    options: ["Roti Prata", "Satay", "Chilli Crab", "Hainanese Chicken Rice"],
    correctAnswer: 3,
    explanation: "Hainanese Chicken Rice is widely considered Singapore's national dish.",
  },
  {
    id: 9,
    question: "Which ethnic groups make up Singapore's multicultural society?",
    options: [
      "Chinese, Malay, Indian, Eurasian",
      "Chinese, Thai, Malay, Arab",
      "Indian, Vietnamese, Malay, Filipino",
      "Malay, Tamil, Korean, Japanese",
    ],
    correctAnswer: 0,
    explanation:
      "Singapore’s society is mainly composed of Chinese, Malay, Indian, and Eurasian groups.",
  },
  {
    id: 10,
    question: "Which shopping street is most famous in Singapore?",
    options: ["Marina Boulevard", "Orchard Road", "Sentosa Walk", "Chinatown Lane"],
    correctAnswer: 1,
    explanation:
      "Orchard Road is the most well-known shopping and entertainment district in Singapore.",
  },
];

export const turkeyQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Turkey?",
    options: ["Istanbul", "Ankara", "Izmir", "Bursa"],
    correctAnswer: 1,
    explanation: "Ankara is the capital of Turkey, while Istanbul is its largest city.",
  },
  {
    id: 2,
    question:
      "Which famous landmark in Istanbul was once a church and a mosque, and is now a museum?",
    options: ["Topkapi Palace", "Blue Mosque", "Hagia Sophia", "Dolmabahce Palace"],
    correctAnswer: 2,
    explanation: "Hagia Sophia has served as a church, mosque, and museum over its long history.",
  },
  {
    id: 3,
    question: "Which strait separates the European and Asian sides of Turkey?",
    options: ["Suez Canal", "Bosporus Strait", "Dardanelles", "Strait of Hormuz"],
    correctAnswer: 1,
    explanation: "The Bosporus Strait divides Istanbul into its European and Asian sides.",
  },
  {
    id: 4,
    question: "Which ancient city in Turkey is famous for the ruins of the Temple of Artemis?",
    options: ["Ephesus", "Troy", "Cappadocia", "Pergamon"],
    correctAnswer: 0,
    explanation:
      "Ephesus was home to the Temple of Artemis, one of the Seven Wonders of the Ancient World.",
  },
  {
    id: 5,
    question: "What is the national sport of Turkey?",
    options: ["Football", "Oil Wrestling", "Basketball", "Archery"],
    correctAnswer: 1,
    explanation: "Traditional Turkish oil wrestling is considered the national sport.",
  },
  {
    id: 6,
    question:
      "Which Turkish region is famous for its fairy chimney rock formations and hot-air balloons?",
    options: ["Pamukkale", "Cappadocia", "Antalya", "Bodrum"],
    correctAnswer: 1,
    explanation: "Cappadocia is known worldwide for its unique rock formations and balloon rides.",
  },
  {
    id: 7,
    question: "What is the official currency of Turkey?",
    options: ["Euro", "Lira", "Dollar", "Ruble"],
    correctAnswer: 1,
    explanation: "The Turkish Lira (TRY) is the official currency of Turkey.",
  },
  {
    id: 8,
    question: "Which empire had Istanbul (then Constantinople) as its capital?",
    options: ["Roman Empire", "Byzantine Empire", "Ottoman Empire", "Persian Empire"],
    correctAnswer: 2,
    explanation: "The Ottoman Empire made Constantinople (now Istanbul) its capital.",
  },
  {
    id: 9,
    question:
      "Which popular dessert made of layers of pastry, nuts, and honey originates from Turkey?",
    options: ["Kunafa", "Baklava", "Lokum", "Halva"],
    correctAnswer: 1,
    explanation: "Baklava is a sweet pastry that is very popular in Turkey.",
  },
  {
    id: 10,
    question: "What is the Turkish name for Turkey?",
    options: ["Turkiye", "Anadolu", "Istanbul", "Osmanli"],
    correctAnswer: 0,
    explanation: "In Turkish, the country is called 'Türkiye'.",
  },
];

export const greeceQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Greece?",
    options: ["Athens", "Sparta", "Delphi", "Thessaloniki"],
    correctAnswer: 0,
    explanation: "Athens is the capital city of Greece and one of the oldest cities in the world.",
  },
  {
    id: 2,
    question: "Which ancient structure in Athens was dedicated to the goddess Athena?",
    options: ["Colosseum", "Parthenon", "Acropolis", "Pantheon"],
    correctAnswer: 1,
    explanation: "The Parthenon, located on the Acropolis, was built for Athena.",
  },
  {
    id: 3,
    question: "Which Greek philosopher taught Alexander the Great?",
    options: ["Socrates", "Plato", "Aristotle", "Pythagoras"],
    correctAnswer: 2,
    explanation: "Aristotle tutored Alexander the Great.",
  },
  {
    id: 4,
    question: "What is the national dish of Greece made with layers of eggplant and meat?",
    options: ["Souvlaki", "Moussaka", "Dolmades", "Gyro"],
    correctAnswer: 1,
    explanation: "Moussaka is a famous Greek layered dish.",
  },
  {
    id: 5,
    question: "Which sea lies to the east of Greece?",
    options: ["Adriatic Sea", "Aegean Sea", "Ionian Sea", "Black Sea"],
    correctAnswer: 1,
    explanation: "The Aegean Sea is located to the east of Greece.",
  },
  {
    id: 6,
    question: "Which event began in ancient Olympia in 776 BCE?",
    options: ["Democracy", "Olympic Games", "Philosophy schools", "Marathons"],
    correctAnswer: 1,
    explanation: "The Olympic Games began in Olympia, Greece.",
  },
  {
    id: 7,
    question: "What is the currency of Greece?",
    options: ["Euro", "Drachma", "Lira", "Pound"],
    correctAnswer: 0,
    explanation: "Greece uses the Euro (€) as its official currency.",
  },
  {
    id: 8,
    question: "Which Greek island is the largest?",
    options: ["Santorini", "Crete", "Rhodes", "Mykonos"],
    correctAnswer: 1,
    explanation: "Crete is the largest Greek island.",
  },
  {
    id: 9,
    question: "Which Greek god is known as the god of the sea?",
    options: ["Zeus", "Apollo", "Poseidon", "Hermes"],
    correctAnswer: 2,
    explanation: "Poseidon is the god of the sea in Greek mythology.",
  },
  {
    id: 10,
    question: "What type of columns are found in classical Greek architecture?",
    options: [
      "Doric, Ionic, Corinthian",
      "Roman, Gothic, Baroque",
      "Byzantine, Ottoman, Modern",
      "Mayan, Inca, Aztec",
    ],
    correctAnswer: 0,
    explanation: "The three main styles of Greek columns are Doric, Ionic, and Corinthian.",
  },
];

export const italyQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Italy?",
    options: ["Milan", "Venice", "Florence", "Rome"],
    correctAnswer: 3,
    explanation: "Rome is the capital of Italy and was the heart of the Roman Empire.",
  },
  {
    id: 2,
    question: "Which Italian city is famous for its canals and gondolas?",
    options: ["Naples", "Venice", "Florence", "Turin"],
    correctAnswer: 1,
    explanation: "Venice is world-famous for its canals and gondola rides.",
  },
  {
    id: 3,
    question: "Which volcano famously destroyed the ancient city of Pompeii?",
    options: ["Etna", "Stromboli", "Vesuvius", "Vulcano"],
    correctAnswer: 2,
    explanation: "Mount Vesuvius erupted in 79 CE, burying Pompeii in ash.",
  },
  {
    id: 4,
    question: "What is Italy’s national dish that consists of pasta, cheese, and tomato sauce?",
    options: ["Pizza", "Risotto", "Lasagna", "Carbonara"],
    correctAnswer: 2,
    explanation: "Lasagna is often considered one of Italy's national dishes.",
  },
  {
    id: 5,
    question: "What is the official currency of Italy?",
    options: ["Lira", "Euro", "Franc", "Pound"],
    correctAnswer: 1,
    explanation: "Italy uses the Euro (€) as its currency.",
  },
  {
    id: 6,
    question: "Which city hosts the Leaning Tower?",
    options: ["Rome", "Florence", "Pisa", "Naples"],
    correctAnswer: 2,
    explanation: "The Leaning Tower of Pisa is one of Italy’s most famous landmarks.",
  },
  {
    id: 7,
    question: "Which Italian region is known for producing Parmesan cheese?",
    options: ["Lombardy", "Emilia-Romagna", "Tuscany", "Veneto"],
    correctAnswer: 1,
    explanation: "Parmigiano-Reggiano originates from the Emilia-Romagna region.",
  },
  {
    id: 8,
    question: "Which famous artist painted the ceiling of the Sistine Chapel?",
    options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"],
    correctAnswer: 1,
    explanation: "Michelangelo painted the Sistine Chapel ceiling.",
  },
  {
    id: 9,
    question: "Which car brand originated in Italy?",
    options: ["Ferrari", "Mercedes", "BMW", "Audi"],
    correctAnswer: 0,
    explanation: "Ferrari is an iconic Italian luxury sports car brand.",
  },
  {
    id: 10,
    question: "What mountain range runs along Italy’s northern border?",
    options: ["Pyrenees", "Alps", "Carpathians", "Apennines"],
    correctAnswer: 1,
    explanation: "The Alps form Italy’s northern border.",
  },
];

export const germanyQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Germany?",
    options: ["Munich", "Berlin", "Frankfurt", "Hamburg"],
    correctAnswer: 1,
    explanation: "Berlin is the capital of Germany.",
  },
  {
    id: 2,
    question: "Which famous wall divided East and West Berlin until 1989?",
    options: ["Great Wall", "Berlin Wall", "Iron Curtain", "Rhine Barrier"],
    correctAnswer: 1,
    explanation: "The Berlin Wall divided the city during the Cold War.",
  },
  {
    id: 3,
    question: "What is Germany’s national drink?",
    options: ["Beer", "Wine", "Vodka", "Cider"],
    correctAnswer: 0,
    explanation: "Beer is deeply ingrained in German culture.",
  },
  {
    id: 4,
    question: "What is the official currency of Germany?",
    options: ["Mark", "Euro", "Franc", "Pound"],
    correctAnswer: 1,
    explanation: "Germany uses the Euro (€) as its currency.",
  },
  {
    id: 5,
    question: "Which festival in Munich is the world’s largest beer festival?",
    options: ["Carnival", "Oktoberfest", "May Day", "Volksfest"],
    correctAnswer: 1,
    explanation: "Oktoberfest in Munich is the world’s largest beer festival.",
  },
  {
    id: 6,
    question: "Which German composer wrote the Ninth Symphony?",
    options: ["Bach", "Beethoven", "Mozart", "Wagner"],
    correctAnswer: 1,
    explanation: "Ludwig van Beethoven composed the Ninth Symphony.",
  },
  {
    id: 7,
    question: "Which car company’s headquarters is in Wolfsburg, Germany?",
    options: ["BMW", "Volkswagen", "Mercedes-Benz", "Porsche"],
    correctAnswer: 1,
    explanation: "Volkswagen is headquartered in Wolfsburg.",
  },
  {
    id: 8,
    question: "What river runs through Cologne?",
    options: ["Danube", "Rhine", "Elbe", "Main"],
    correctAnswer: 1,
    explanation: "The Rhine River flows through Cologne.",
  },
  {
    id: 9,
    question: "Which Black Forest dessert comes from Germany?",
    options: ["Sachertorte", "Black Forest Cake", "Apple Strudel", "Stollen"],
    correctAnswer: 1,
    explanation: "Black Forest Cake (Schwarzwälder Kirschtorte) is a famous German dessert.",
  },
  {
    id: 10,
    question: "What is Germany’s national animal?",
    options: ["Eagle", "Bear", "Lion", "Horse"],
    correctAnswer: 0,
    explanation: "The eagle is the national symbol of Germany.",
  },
];

export const franceQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of France?",
    options: ["Paris", "Lyon", "Marseille", "Nice"],
    correctAnswer: 0,
    explanation: "Paris is the capital and largest city of France.",
  },
  {
    id: 2,
    question: "Which famous tower is located in Paris?",
    options: ["Eiffel Tower", "Big Ben", "Leaning Tower", "CN Tower"],
    correctAnswer: 0,
    explanation: "The Eiffel Tower is the most iconic symbol of Paris.",
  },
  {
    id: 3,
    question: "What is the official currency of France?",
    options: ["Franc", "Euro", "Pound", "Lira"],
    correctAnswer: 1,
    explanation: "France uses the Euro (€) as its official currency.",
  },
  {
    id: 4,
    question: "Which French region is known for producing Champagne?",
    options: ["Bordeaux", "Champagne", "Provence", "Burgundy"],
    correctAnswer: 1,
    explanation: "The Champagne region produces the famous sparkling wine.",
  },
  {
    id: 5,
    question: "Which French queen was famously associated with the phrase 'Let them eat cake'?",
    options: ["Catherine de Medici", "Joan of Arc", "Marie Antoinette", "Anne of Austria"],
    correctAnswer: 2,
    explanation: "Marie Antoinette is often (though likely falsely) credited with this phrase.",
  },
  {
    id: 6,
    question: "Which museum in Paris houses the Mona Lisa?",
    options: ["Orsay", "Louvre", "Pompidou", "Versailles"],
    correctAnswer: 1,
    explanation: "The Louvre Museum is home to the Mona Lisa.",
  },
  {
    id: 7,
    question: "What is the French national holiday on July 14 called?",
    options: ["Bastille Day", "Victory Day", "Liberty Day", "Revolution Day"],
    correctAnswer: 0,
    explanation: "Bastille Day commemorates the storming of the Bastille in 1789.",
  },
  {
    id: 8,
    question: "Which French fashion designer is famous for the 'Little Black Dress'?",
    options: ["Chanel", "Dior", "Louis Vuitton", "Yves Saint Laurent"],
    correctAnswer: 0,
    explanation: "Coco Chanel popularized the Little Black Dress.",
  },
  {
    id: 9,
    question: "Which river flows through Paris?",
    options: ["Loire", "Seine", "Rhône", "Garonne"],
    correctAnswer: 1,
    explanation: "The Seine River runs through Paris.",
  },
  {
    id: 10,
    question: "What is France’s national motto?",
    options: [
      "Freedom, Equality, Brotherhood",
      "Strength, Honor, Unity",
      "Justice, Peace, Liberty",
      "Pride, Loyalty, Duty",
    ],
    correctAnswer: 0,
    explanation:
      "The French motto is 'Liberté, Égalité, Fraternité' (Freedom, Equality, Brotherhood).",
  },
];

export const spainQuestions: TriviaQuestion[] = [
  {
    id: 1,
    question: "What is the capital city of Spain?",
    options: ["Barcelona", "Madrid", "Seville", "Valencia"],
    correctAnswer: 1,
    explanation: "Madrid is the capital of Spain.",
  },
  {
    id: 2,
    question: "Which Spanish city is famous for its Sagrada Familia basilica?",
    options: ["Madrid", "Barcelona", "Granada", "Toledo"],
    correctAnswer: 1,
    explanation: "Barcelona is home to Gaudí’s masterpiece, the Sagrada Familia.",
  },
  {
    id: 3,
    question: "Which dance and music style originated in Andalusia, Spain?",
    options: ["Tango", "Flamenco", "Samba", "Fado"],
    correctAnswer: 1,
    explanation: "Flamenco is a passionate dance and music form from Andalusia.",
  },
  {
    id: 4,
    question: "What is the official currency of Spain?",
    options: ["Peseta", "Euro", "Dollar", "Franc"],
    correctAnswer: 1,
    explanation: "Spain uses the Euro (€) as its currency.",
  },
  {
    id: 5,
    question: "Which Spanish festival involves running in front of bulls?",
    options: ["La Tomatina", "San Fermín", "Semana Santa", "Las Fallas"],
    correctAnswer: 1,
    explanation: "The Running of the Bulls takes place during the San Fermín festival in Pamplona.",
  },
  {
    id: 6,
    question: "Which Spanish dish is made with rice, saffron, and seafood or meat?",
    options: ["Tapas", "Gazpacho", "Paella", "Churros"],
    correctAnswer: 2,
    explanation: "Paella is Spain’s most famous rice dish.",
  },
  {
    id: 7,
    question: "Which famous Spanish artist painted 'Guernica'?",
    options: ["Dalí", "Picasso", "Velázquez", "Goya"],
    correctAnswer: 1,
    explanation: "Pablo Picasso painted the anti-war masterpiece 'Guernica'.",
  },
  {
    id: 8,
    question: "Which island group belongs to Spain and lies off the northwest coast of Africa?",
    options: ["Balearic Islands", "Canary Islands", "Azores", "Madeira"],
    correctAnswer: 1,
    explanation: "The Canary Islands are part of Spain and lie near Africa.",
  },
  {
    id: 9,
    question: "Which football clubs are Spain’s most famous rivals?",
    options: [
      "Real Madrid & Barcelona",
      "Sevilla & Valencia",
      "Atletico & Villarreal",
      "Bilbao & Betis",
    ],
    correctAnswer: 0,
    explanation: "The rivalry between Real Madrid and Barcelona is known as 'El Clásico'.",
  },
  {
    id: 10,
    question:
      "Which Spanish painter is known for his surrealist works like 'The Persistence of Memory'?",
    options: ["Picasso", "Goya", "Dalí", "Miró"],
    correctAnswer: 2,
    explanation: "Salvador Dalí was a famous surrealist artist from Spain.",
  },
];
